/*
 * @Author: wanghao wanghao@oureman.com
 * @Date: 2023-04-23 18:07:41
 * @LastEditors: wanghao wanghao@oureman.com
 * @LastEditTime: 2023-05-09 15:30:54
 * @FilePath: /mesui/lib/pages/configAutomation/annotationTextMap.dart
 * @Description: 注释文本映射
 */

//  获取字段备注
String getAnnotationText(String field, String section, String configName) {
  return annotationTextMap['$configName-$section-$field'] ??
      getScalableAnnotationText(field, section, configName);
}

String getScalableAnnotationText(
    String field, String section, String configName) {
  var reg = RegExp(r'^[a-zA-Z]+\d+$');
  var normalSection;
  if (reg.hasMatch(section)) {
    var reg2 = RegExp(r'[a-zA-Z]+');
    // 将首部英文提取出来
    var match = reg2.firstMatch(section);
    normalSection = match?.group(0);
  } else {
    normalSection = section;
  }
  return annotationTextMap['$configName-$normalSection-$field'] ?? '';
}

Map<String, String> annotationTextMap = {
  // plcAddress
  'plcAddress-Plc_M_Block-CMD_ID_R_OPUTS': '读取多个I点',
  'plcAddress-Plc_M_Block-CMD_ID_R_IPUTS': '读取多个O点',
  'plcAddress-Plc_M_Block-CMD_ID_R_REGS': '读取多个寄存器',
  'plcAddress-Plc_M_Block-CMD_ID_W_OPUT': '写单个O点',
  'plcAddress-Plc_M_Block-CMD_ID_W_OPUTS': '写多个O点',
  'plcAddress-Plc_M_Block-CMD_ID_W_REGS': '写多寄存器',
  'plcAddress-Plc_M_Block-RobotMainPrgRun': '机器人主程序',
  'plcAddress-Plc_M_Block-RobotPause': '机器人暂停继续',
  'plcAddress-Plc_M_Block-Buzzer': '蜂鸣器地址',
  'plcAddress-Plc_M_Block-GuideRun': '导轨运动标识',
  'plcAddress-Plc_M_Block-ServoAlarmReset': '伺服报警复位',
  'plcAddress-Plc_M_Block-OpenDoor': '货架电磁门开门',
  'plcAddress-Plc_M_Block-OpenDoor2': '货架电磁门开门2',
  'plcAddress-Plc_M_Block-MachineRun': '机床启动的起始地址',
  'plcAddress-Plc_M_Block-MachineRest': '机床复位的起始地址',
  'plcAddress-Plc_M_Block-MahicneNumToPlc': '执行机器人任务时传递给PLC的机床号地址',
  'plcAddress-Plc_M_Block-StorageNumToPlc': '执行机器人任务时传递给PLC的货位号地址',
  'plcAddress-Plc_M_Block-ShelfUpLineCtrl': '货架上下线控制',
  'plcAddress-Plc_M_Block-MachineUpLineCtrl': '机床上下线控制',
  'plcAddress-Plc_M_Block-MachineStatusLightCtrl': '机床状态灯的控制',
  'plcAddress-Plc_M_Block-RotatShelfRun': '启动旋转货架旋转',
  'plcAddress-Plc_M_Block-RobotTaskType': '任务类型',
  'plcAddress-Plc_M_Block-TakeStorageNum': '取货位号',
  'plcAddress-Plc_M_Block-PutStorageNum': '放货位号',
  'plcAddress-Plc_M_Block-CmmMachineStatusByIO': 'IO给出的CMM机床状态',
  'plcAddress-Plc_M_Block-TransferShelfOnLineAsk': '装载站上线请求',
  'plcAddress-Plc_M_Block-TransferShelfOffLineAsk': '装载站下线请求',
  'plcAddress-Plc_M_Block-TransferStorageSensorStatus': '装载站货位状态',
  'plcAddress-Plc_M_Block-TransferShelfButtonStatus': '装载站货架按钮灯',
  'plcAddress-Plc_M_Block-TransferStorageRotatLocationStatus': '装载站旋定位状态',
  'plcAddress-Plc_M_Block-TransferDoorStatus': '装载站门状态',
  'plcAddress-Plc_M_Block-OilGrooveUpCtrl': '油槽升降地址',
  'plcAddress-Plc_M_Block-OilGroCtrlMacNum': '配合油槽升降的机床号',
  'plcAddress-Plc_M_Block-StopBlow': '机床吹气',
  'plcAddress-Plc_M_Block-ConnectStationOffX': '给机器人写接驳站偏移量X的起始地址',
  'plcAddress-Plc_M_Block-ConnectStationOffY': '给机器人写接驳站偏移量Y的起始地址',
  'plcAddress-Plc_M_Block-ConnectStationOffZ': '给机器人写接驳站偏移量Z的起始地址',
  'plcAddress-Plc_M_Block-MacStartPumpingAdd': '火花机抽油启动地址',
  'plcAddress-Plc_M_Block-MacPumpingStopTime': '火花机抽油时间地址',
  'plcAddress-Plc_M_Block-TranSportStorageStatus': '配合武城职接驳站单独拎出来用于判断接驳站货位状态',
  'plcAddress-Plc_M_Block-BaseInfo': '基础信息, 同时也是监控区的起始地址',
  'plcAddress-Plc_M_Block-ShelfDoor': '货架门',
  'plcAddress-Plc_M_Block-ShelfDoor2': '货架门2',
  'plcAddress-Plc_M_Block-MacFenceDoorStatus': '机床围栏门状态',
  'plcAddress-Plc_M_Block-MacFenceDoorBrakingStatus': '机床围栏门急停',
  'plcAddress-Plc_M_Block-FencePneumaticDoorStatus': '机床外围的安全气动门状态(由plc控制)',
  'plcAddress-Plc_M_Block-FenceDoor': '围栏门',
  'plcAddress-Plc_M_Block-AccompanyPlat': '随行台and导轨',
  'plcAddress-Plc_M_Block-MachineFinish': 'PLC控制启动的机床',
  'plcAddress-Plc_M_Block-MachineFinish2': 'PLC控制启动的机床2',
  'plcAddress-Plc_M_Block-ShelfOnlineAsk': '货架上线请求',
  'plcAddress-Plc_M_Block-ShelfOnlineAsk2': '货架上线请求2',
  'plcAddress-Plc_M_Block-ShelfOfflineAsk': '货架下线请求',
  'plcAddress-Plc_M_Block-ShelfOfflineAsk2': '货架下线请求2',
  'plcAddress-Plc_M_Block-ShelfOpenDoorAsk': '货架开门信号',
  'plcAddress-Plc_M_Block-ShelfEmergencyStop': '货架急停',
  'plcAddress-Plc_M_Block-ShelfEmergencyStop2': '货架急停2',
  'plcAddress-Plc_M_Block-FenceEmergencyStop': '电脑柜and围栏门急停',
  'plcAddress-Plc_M_Block-ChuckLockUnLockStatus': '卡盘锁紧松开状态',
  'plcAddress-Plc_M_Block-ChuckAirtightness': '机床卡盘气密性状态',
  'plcAddress-Plc_M_Block-ChuckAirtightness2': '机床卡盘气密性状态2',
  'plcAddress-Plc_M_Block-ChuckOpenCloseStatus': '卡盘锁紧/松开功能异常',
  'plcAddress-Plc_M_Block-ChuckOpenCloseStatus2': '卡盘锁紧/松开功能异常2',
  'plcAddress-Plc_M_Block-PressureValue': '气压值',
  'plcAddress-Plc_M_Block-MacAutoDoorStatus': '机床自动门异常',
  'plcAddress-Plc_M_Block-MacAutoDoorStatus2': '机床自动门异常2',
  'plcAddress-Plc_M_Block-MacOriginPosCheck': '机床原点检测',
  'plcAddress-Plc_M_Block-MacOriginPosCheck2': '机床原点检测2',
  'plcAddress-Plc_M_Block-MacOnlineAsk': '机床上线请求',
  'plcAddress-Plc_M_Block-MacOnlineAsk2': '机床上线请求2',
  'plcAddress-Plc_M_Block-MacOfflineAsk': '机床下线请求',
  'plcAddress-Plc_M_Block-MacOfflineAsk2': '机床下线请求2',
  'plcAddress-Plc_M_Block-MachineError': '机床报警',
  'plcAddress-Plc_M_Block-MachineError2': '机床报警2',
  'plcAddress-Plc_M_Block-RotatShelfScanFinish': '旋转货架扫码完成',
  'plcAddress-Plc_M_Block-RotatShelfScanFinish2': '旋转货架扫码完成2',
  'plcAddress-Plc_M_Block-ShelfTricolorLampState': '货架三色灯状态',
  'plcAddress-Plc_M_Block-MacObstructionCheck': '机床上料阻碍标识检测',
  'plcAddress-Plc_M_Block-MacObstructionCheck2': '机床上料阻碍标识检测2',
  'plcAddress-Plc_M_Block-MacWasteMonitor': '机床废料监控',
  'plcAddress-Plc_M_Block-MacWasteMonitor2': '机床废料监控2',
  'plcAddress-Plc_M_Block-StorageSensorStatus': '货位状态地址',
  'plcAddress-Plc_M_Block-StorageLightCtrl': '货位灯的地址',
  'plcAddress-Plc_M_Block-CMD_IDF_PRESSURE': '压力标识',
  'plcAddress-Plc_M_Block-CMD_IDF_CLAMP': '卡爪夹取标识',
  'plcAddress-Plc_M_Block-CMD_IDF_ROBOT_CONTROL_CABINET': '机器人控制柜标识',
  'plcAddress-Plc_M_Block-CMD_IDF_ROBOT_HANDY_PANEL': '机器人手持盒标识',
  'plcAddress-Plc_M_Block-CMD_IDF_CHUCK_SCAN': '卡盘电极扫描标识',
  'plcAddress-Plc_M_Block-CMD_IDF_ROBOT_SAFE_POSITION': '机器人安全位置',
  'plcAddress-PlcDefinition-OkLight': '货位灯颜色的定义 1:亮绿灯，2:亮红灯,3:亮黄灯',
  'plcAddress-PlcDefinition-NgLight': '货位灯颜色的定义 1:亮绿灯，2:亮红灯,3:亮黄灯',
  'plcAddress-PlcDefinition-WarnLight': '货位灯颜色的定义 1:亮绿灯，2:亮红灯,3:亮黄灯',
  'plcAddress-PlcDbBlock-RfidRead': '对射货架货架初始读取地址',
  'plcAddress-RobotTaskPosition-Ask': '机器人与软件交互状态（ASK）',
  'plcAddress-RobotTaskPosition-Type': '任务类型(TYPE)',
  'plcAddress-RobotTaskPosition-TakeNum': '取货位号,（从货架上取）(TAKE)',
  'plcAddress-RobotTaskPosition-TakeShelfNum': '取货架号',
  'plcAddress-RobotTaskPosition-TakeStorageType': '取货位类型',
  'plcAddress-RobotTaskPosition-PutMachineNum': '放机床号（放到机床上）',
  'plcAddress-RobotTaskPosition-PutDirection': '放料基准角(上料到机床，对应放机床号)',
  'plcAddress-RobotTaskPosition-TakeMachineNum': '取机床号（从机床上取走）',
  'plcAddress-RobotTaskPosition-TakeDirection': '取料基准角(从机床上取走，对应取机床号)',
  'plcAddress-RobotTaskPosition-PutNum': '放货位号(PUT)（放回货位）',
  'plcAddress-RobotTaskPosition-PutShelfNum': '放货架号',
  'plcAddress-RobotTaskPosition-PutStorageType': '放货位类型',
  'plcAddress-RobotTaskPosition-Finish': '任务完成（FINISH）',
  'plcAddress-RobotTaskPosition-LoopFinish': '结束机器人当前主程序（跳过FINISH）',
  'plcAddress-RobotTaskPosition-OnScanChuck': '扫描卡盘时处理的位置',
  'plcAddress-RobotTaskPosition-TakeWight': '取工件的重量',
  'plcAddress-RobotTaskPosition-PutWeight': '放工件的重量',
  'plcAddress-RobotTaskPosition-WorkpiecePosOffsetX': '接驳站视觉定位偏移量X',
  'plcAddress-RobotTaskPosition-WorkpiecePosOffsetY': '接驳站视觉定位偏移量Y',
  'plcAddress-RobotTaskPosition-WorkpiecePosOffsetZ': '接驳站视觉定位偏移量Z',
  'plcAddress-JumpRobotTaskNode-OnJumpRobotTask': '需要跳过的机器人任务任务码-任务码-任务码-任务码',
  // userConfig
  'userConfig-MachineInfo-ServiceAddr': '机床IP（如系统是HDH,此处配置连接名）',
  'userConfig-MachineInfo-ServicePort': '机床端口',
  'userConfig-MachineInfo-ServiceMonitorPort': '机床的第二个端口（一般不用）',
  'userConfig-MachineInfo-MacDefaultConnect': '软件开启时触发',
  'userConfig-MachineInfo-ExtServerConnectMak': '外部服务器连接标识',
  'userConfig-MachineInfo-ExtServiceAddr':
      '外部连接服务器IP    (因为实际项目中直接使用蔡司本身结果的几乎没有都需要第三方的进行结果分析)',
  'userConfig-MachineInfo-ExtServicePort': '外部连接服务器端口',
  'userConfig-MachineInfo-FtpAddr': '机床FTP服务器IP',
  'userConfig-MachineInfo-FtpPort': '机床FTP服务器端口',
  'userConfig-MachineInfo-FtpUser': '机床FTP服务器用户名',
  'userConfig-MachineInfo-FtpPwd': '机床FTP服务器密码',
  'userConfig-MachineInfo-FtpCodeType': '机床FTP编码类型',
  'userConfig-MachineInfo-FtpTransferType': '读取FTP信息所使用的本地编码',
  'userConfig-MachineInfo-FtpPath': '机床FTP服务器程式的默认访问路径',
  'userConfig-MachineInfo-FtpRootDir': '机床FTP根目录',
  'userConfig-MachineInfo-MachineNum': '机床号作为机床识别码(和机器人上料无关)',
  'userConfig-MachineInfo-ChuckNum':
      '机床卡盘号信息，注释：1号电极卡盘坐标系名称G54，2号钢件卡盘坐标系名称G55；卡盘类型 0任意1电极2钢件',
  'userConfig-MachineInfo-MacBrand':
      '机床品牌(除了系统类型为FANUC的机床，其他机床可不配或者配成和系统类型一样的)',
  'userConfig-MachineInfo-MachineType': '机床类型',
  'userConfig-MachineInfo-MacProcessLimit': '机床限制工艺',
  'userConfig-MachineInfo-MachineName': '机床名称，不同机床间不能重复',
  'userConfig-MachineInfo-MacEscapeChineName': '机床转义名称',
  'userConfig-MachineInfo-MacSystemType': '机床系统类型',
  'userConfig-MachineInfo-MacSystemVersion': '机床系统版本',
  'userConfig-MachineInfo-MainPrgFinishMark': '主程序结束标志',
  'userConfig-MachineInfo-SubPrgFinishMark': '子程序结束标志',
  'userConfig-MachineInfo-SrcPrgServerNodeName':
      '源程序服务节点名称，在此节点名称下获取对应的信息和后缀名(服务器上源程序信息)',
  'userConfig-MachineInfo-SrcPrgLocalNodeName':
      '源程序本地节点名称，在此节点下获取对应的路径的信息（配置机床节点内）',
  'userConfig-MachineInfo-ExecPrgServerNodeName':
      '执行程序服务节点名称，在此节点名称下获取对应的信息和后缀名(服务器上执行程序信息)',
  'userConfig-MachineInfo-ExecPrgLocalNodeName':
      '执行程序本地节点名称，在此节点下获取对应的路径的信息（配置机床节点内）',
  'userConfig-MachineInfo-OutPutNodeName':
      '执行程序本地节点名称，在此节点下获取对应的路径的信息，用法：将Zeiss检测结果输出至eact指定路径',
  'userConfig-MachineInfo-EactUnitePrg': '程式是否由Eact合并',
  'userConfig-MachineInfo-MachineMarkCode':
      '机床标识码，供半自动化合并程式使用机床标识码，对应eact 的CMMBarCode或者 CNCBarCode',
  'userConfig-MachineInfo-CncPrgCallMode': '加工机床程序调用模式,为空默认值MAIN',
  'userConfig-MachineInfo-ModifyInfoAddPositionMode': '修改程序内容插入位置',
  'userConfig-MachineInfo-MainPrgTopInsertMark':
      '主程式顶部插入标识(所有修改类型共用该标识)，尾部插入标识默认是 MainPrgFinishMark',
  'userConfig-MachineInfo-MainPrgGoOrginAddMode': '主程序回原点内容添加方式',
  'userConfig-MachineInfo-SubPrgTopInsertMark':
      '子程式顶部插入标识(所有修改类型共用该标识)，尾部插入标识默认是 SubPrgFinishMark',
  'userConfig-MachineInfo-SubPrgGoOrginAddMode': '子程序回原点内容添加方式',
  'userConfig-MachineInfo-SubInsertDoorCtrlMode':
      '在子程序调用模式下且AutoDoor=1时使用，默认不添加开关门指令',
  'userConfig-MachineInfo-ElecHeightAddMode': '是否添加电极测高(测高：不带拉钉的夹具底部至电极头部的高度)',
  'userConfig-MachineInfo-SteelSetOffAddMode': '是否添加钢件偏移量',
  'userConfig-MachineInfo-SteelSetOffAddPos': '添加位置',
  'userConfig-MachineInfo-OffsetStartMark': '偏移量开始添加标识文本',
  'userConfig-MachineInfo-OffsetEndMark': '偏移量结束添加标识文本',
  'userConfig-MachineInfo-MacOrgionInterceptStartMark': '回原点截取开始文本标识',
  'userConfig-MachineInfo-MacOrgionInterceptEndMark': '回原点截取结束文本标识',
  'userConfig-MachineInfo-MacOrgoinInsertMark': '回原点插入位置文本标志',
  'userConfig-MachineInfo-RepSpecifiedContentMode': '替换程序中指定的内容模式',
  'userConfig-MachineInfo-RepSpecifiedContentStartNum': '开始替换的位置(就是从第几个开始替换)',
  'userConfig-MachineInfo-RepSpecifiedContentNum': '替换的次数',
  'userConfig-MachineInfo-RepSpecifiedContentOldMark': '需要替换的原始内容',
  'userConfig-MachineInfo-RepSpecifiedContentNewMark': '需要替换的新内容',
  'userConfig-MachineInfo-RotatCoordinateAddMode': '程序添加坐标旋转模式',
  'userConfig-MachineInfo-RotatCoordinateAddNum': '程序添加坐标旋转次数',
  'userConfig-MachineInfo-RotatCoordinateMark': '程序坐标旋转添加文本',
  'userConfig-MachineInfo-RotatCoordinateFlag': '程序坐标旋转标识文本',
  'userConfig-MachineInfo-ReturnRotatCoordinateMode': '程序取消坐标旋转模式',
  'userConfig-MachineInfo-ReturnRotatCoordinateNum': '程序添加坐标旋转次数',
  'userConfig-MachineInfo-ReturnRotatCoordinateMark': '程序坐标旋转取消添加文本',
  'userConfig-MachineInfo-ReturnRotatCoordinateFlag': '程序坐标旋转取消标识文本',
  'userConfig-MachineInfo-ToolReplaceMode': '刀具替换标识',
  'userConfig-MachineInfo-ToolReplaceStyle': '替换样式',
  'userConfig-MachineInfo-Tool_H_ReplaceMode': '刀补替换模式',
  'userConfig-MachineInfo-Tool_H_ReplaceStyle': '刀补替换样式',
  'userConfig-MachineInfo-DelTopAddMode': '是否需要添加杀顶',
  'userConfig-MachineInfo-DelTopMark': '添加杀顶开始文本标志',
  'userConfig-MachineInfo-DelTopToolNums': '杀顶用到的刀号',
  'userConfig-MachineInfo-KillTopPrgName': '杀顶头部程序名',
  'userConfig-MachineInfo-CheckCoordSystem': '卡盘补正坐标系',
  'userConfig-MachineInfo-KillToolDiameter': '杀顶刀的直径(mm)',
  'userConfig-MachineInfo-KillToolWidth': '杀顶每一刀Y方向或者X方向走的宽度(mm)',
  'userConfig-MachineInfo-KillToolHight': '杀顶Z方向每一刀下的深度[最好带上正负号](mm)',
  'userConfig-MachineInfo-ZCorrectionValueMode': '卡盘Z方向补正值添加标识',
  'userConfig-MachineInfo-szZCorrectionValueMark': '卡盘Z方向补正添加标识文本',
  'userConfig-MachineInfo-ZCorrectionMargin': '补正余量',
  'userConfig-MachineInfo-ChuckCoordZValue': '卡盘Z值',
  'userConfig-MachineInfo-MacOilLiftPumpMode': '机床添加升油泵标志',
  'userConfig-MachineInfo-MacOilLiftPumpMark': '机床添加升油泵标识文本',
  'userConfig-MachineInfo-SubPrgFinishReplaceMode': '子程序结尾替换为回到主程序的标志',
  'userConfig-MachineInfo-SubPrgFinishReplaceMark': '子程序结尾替换为回到主程序的标识文本',
  'userConfig-MachineInfo-CoordinatePeplaceMode': '坐标系替换标志',
  'userConfig-MachineInfo-CoordinatePeplaceNum': '坐标替换次数',
  'userConfig-MachineInfo-CoordinatePeplaceMark': '坐标系替换文本，程序里面原来的坐标系名称',
  'userConfig-MachineInfo-AddPrgLineNumNode': '程序添加行号的标志',
  'userConfig-MachineInfo-DeleteSpecifiedContentMode': '删除程序中的指定内容标志',
  'userConfig-MachineInfo-DeleteSpecifiedContentNum': '删除程序指定内容的次数',
  'userConfig-MachineInfo-DeleteSpecifiedContentMark': '删除程序中的指定内容',
  'userConfig-MachineInfo-AddProgramNameMode': '程序开头是否加主程序名',
  'userConfig-MachineInfo-AddProgramNameMak': '程序名出现%',
  'userConfig-MachineInfo-IsRemoveSpacesMode': '是否去掉空格',
  'userConfig-MachineInfo-AddClampStatusMode': '添加夹具状态标志',
  'userConfig-MachineInfo-ClampCloseMark': '夹具夹紧',
  'userConfig-MachineInfo-ClampRelaxMark': '夹具放松',
  'userConfig-MachineInfo-MainPrgUpMode': '主程序上传方式',
  'userConfig-MachineInfo-SubPrgUpMode': '子程序上传方式',
  'userConfig-MachineInfo-SubUpPrgNumbarMode': '子程序个数上传模式',
  'userConfig-MachineInfo-MacMainPrgPath': '机床主程式上传路径（共享或者机床路径）',
  'userConfig-MachineInfo-MacSubPrgPath': '机床子程式上传路径（共享或者机床路径可与上个路径一样）',
  'userConfig-MachineInfo-MainPrgName':
      '机床主程序命名   该程序可直接进行加工，也可以通过M198调用子程序进行加工',
  'userConfig-MachineInfo-MacFirstSubPrgName': '机床子程序命名  机床M198运行会用到子程序',
  'userConfig-MachineInfo-MacOriginPrgName':
      '机床原点程式命名  O3333或O3333.nc ，根据机床识别要求决定是否带后缀名',
  'userConfig-MachineInfo-FileExtension':
      '机床程序扩展名 .(检测项目配置提前上料文件的后缀名，加工会自动读取主程序后缀名给其赋值)',
  'userConfig-MachineInfo-CleanPrgName':
      '机床吹气清洁程序命名(默认放在本地Origin目录下)，注意，仅用于子程序，当作最后一把刀',
  'userConfig-MachineInfo-CleanChuckPrgName':
      '机床清洁卡盘程序命名(默认放在本地Origin目录下)，下料后调用',
  'userConfig-MachineInfo-SteelPosBallPrgName': '钢件分中程序名',
  'userConfig-MachineInfo-SteelCheckPrgName': '钢件检测程序名',
  'userConfig-MachineInfo-CopyMacCheckResultFileMark': '在机检测结果文件是否拷贝',
  'userConfig-MachineInfo-OnMacCheckResultFilePath': '在机检测结果文件路径',
  'userConfig-MachineInfo-CmmResultName': '在机检测结果文件名称',
  'userConfig-MachineInfo-AutoDoor': '自动门',
  'userConfig-MachineInfo-OpenDoorComm': '机床开门M指令 合并到NC程式会用到(AutoDoor=1时使用)',
  'userConfig-MachineInfo-CloseDoorComm': '机床关门M指令 合并到NC程式会用到(AutoDoor=1时使用)',
  'userConfig-MachineInfo-OrginAbsoluteType': '坐标类型',
  'userConfig-MachineInfo-OrginAbsoluteX': '用于机器人上料时的机床的坐标X',
  'userConfig-MachineInfo-OrginAbsoluteY': '用于机器人上料时的机床的坐标Y',
  'userConfig-MachineInfo-OrginAbsoluteZ': '用于机器人上料时的机床的坐标Z',
  'userConfig-MachineInfo-OrginAbsoluteU': '用于机器人上料时的机床的坐标U',
  'userConfig-MachineInfo-MacPosX': '电极原点坐标X(不同类型的坐标之间用 & 隔开,类型和坐标之前用 #隔开)',
  'userConfig-MachineInfo-MacPosY': '电极原点坐标Y(不同类型的坐标之间用 & 隔开,类型和坐标之前用 #隔开)',
  'userConfig-MachineInfo-MacPosZ': '电极原点坐标Z(不同类型的坐标之间用 & 隔开,类型和坐标之前用 #隔开)',
  'userConfig-MachineInfo-MacPosU': '电极原点坐标U(不同类型的坐标之间用 & 隔开,类型和坐标之前用 #隔开)',
  'userConfig-MachineInfo-MacPosA': '电极原点坐标A(不同类型的坐标之间用 & 隔开,类型和坐标之前用 #隔开)',
  'userConfig-MachineInfo-MacPosW': '电极原点坐标W(不同类型的坐标之间用 & 隔开,类型和坐标之前用 #隔开)',
  'userConfig-MachineInfo-MacOriginPrgNameInfo': '机床原点程序名称信息',
  'userConfig-MachineInfo-OrginAbsoluteW': '台一火花机油槽高度要用到',
  'userConfig-MachineInfo-MachineAheadTask':
      '提前上料标志（没有提前上料的机床这里一定要是0，目前只有牧野和检测的机床支持提前上料的配置）',
  'userConfig-MachineInfo-MachineAheadLine': '提前上料的行数或者蔡司提前上料的点数',
  'userConfig-MachineInfo-MacBlowMode': '机床吹气的标志',
  'userConfig-MachineInfo-MacBlowTime': '吹气时间配置(单位：秒)(吹气时常软件控制)',
  'userConfig-MachineInfo-MacBlowAheadLine':
      '机床提前吹气的行数:程序加工倒数的行数 例如：程序一共有13500行 如果配置500 表示程序加工走到13000行的时候开始吹气',
  'userConfig-MachineInfo-AutoOfflineType': '单个工件加工完后机床下线控制',
  'userConfig-MachineInfo-MachineAxes':
      '机床轴数，FANUC系统类型的机床机床品牌为FANUC时，有两轴机床（车床）和三轴机床（铣床），五轴（线割）',
  'userConfig-MachineInfo-MacFenceDoorExistMark': '床围栏门存在标志，联塑项目配置 1，其他项目都配 0',
  'userConfig-MachineInfo-MacReadAxesMacroMark': '读取机床轴的宏变量标志',
  'userConfig-MachineInfo-IsWriteAxesMacroToSqlDB': '是否将轴宏变量写入数据库',
  'userConfig-MachineInfo-ReadMacroPosX': 'X方向偏移量位置',
  'userConfig-MachineInfo-ReadMacroPosY': 'Y方向偏移量位置',
  'userConfig-MachineInfo-ReadMacroPosZ': 'Z方向偏移量位置',
  'userConfig-MachineInfo-MacReadRotateMacroMark': '读取机床旋转的宏变量标志',
  'userConfig-MachineInfo-IsWriteRotateMacroToSqlDB': '是否将旋转宏变量写入数据库',
  'userConfig-MachineInfo-ReadRotateMacroPos': 'R方向(旋转)偏移量位置',
  'userConfig-MachineInfo-RotateOffsetAddMode': '是否添加旋转角度偏移量',
  'userConfig-MachineInfo-RotateOffsetAddPos': '添加位置',
  'userConfig-MachineInfo-MacMonitorId': '机床监控ID',
  'userConfig-MachineInfo-MacMergerProgramMark': '机床合并程序',
  'userConfig-MachineInfo-MacCloseDoorPrgName': '机床关门程序名称',
  'userConfig-MachineInfo-ToolLifeOverflowOffineMark': '刀具寿命到期机床离线标志',
  'userConfig-MachineInfo-WorkTimeLowerLimit':
      '工作时间最低限制，低于此时间，不记录到寿命当中，单位：秒 （1分钟 = 60秒）',
  'userConfig-MachineInfo-MacCleanToolPrgName': '机床清洁刀具程序名称',
  'userConfig-MachineInfo-CopyCmmResultMark': '检测结果是否需要拷贝到服务器',
  // 'userConfig-MachineInfo-CmmResultName': '检测结果名',
  'userConfig-MachineInfo-ReadMacroStartPos': '读取 检测点开始 宏变量位置',
  'userConfig-MachineInfo-MacCmmCheckPosMacroPos': '读取宏变量检测点位置,(铸造读取多个点，用& 隔开)',
  'userConfig-MachineInfo-MacCmmResultMacroPos': '读取 检测结果 宏变量位置',
  'userConfig-MachineInfo-CmmResultFilePathPos': '检测结果文件路径位置',
  'userConfig-MachineInfo-MacExistToolManagement': '机床是否存在刀具管理',
  'userConfig-MachineInfo-ToolOpenPermissionMark': '机床刀具权限 开通标志',
  'userConfig-MachineInfo-MacExceptionHandle': '火花机放电异常后钢件是否下料',
  'userConfig-MachineInfo-MacFinishNotToCleanMac': '机床完成是否上清洗机',
  'userConfig-MachineInfo-MacStartWaitTime': '机床启动后等待时长',
  'userConfig-MachineInfo-AheadTaskMonitorFolder':
      '提前任务监控文件夹，CMM快检测完成时，eact会在该文件夹下生成txt通知eatm',
  'userConfig-MachineInfo-ZeissStartFileFolder':
      '创建蔡司startinfo.txt 启动文件的路径(若不在本机上，则为共享路径)',
  'userConfig-MachineInfo-ZeissConnectMode': '仅ZEISS检测使用',
  'userConfig-MachineInfo-CmmDriveMode': '仅用于检测机床驱动模式',
  'userConfig-MachineInfo-OilGrooveCtrlType': '用于火花机油槽的驱动',
  'userConfig-MachineInfo-IsAutoMachineOnline': '机床上线按钮和软件界面的上线按钮是否关联上线',
  'userConfig-MachineInfo-ToolMagazineSize': '刀库上限, 为0时 不判断电极与刀库上限的关系',
  'userConfig-MachineInfo-EAtmMacDataCollectRange': '线内机床采集范围',
  'userConfig-MachineInfo-MacWaitFinishTime': '机床超时未完成检测一个点需要的时间(单位:秒)',
  'userConfig-MachineInfo-ChuckScanJustAnyone':
      '标记初始上料前，机床内的卡盘是否需全部扫描。还是任意扫描某一个卡盘即可。精英电极加工配置 1',
  'userConfig-MachineInfo-WorkSteelAbalmIsPutDown': '钢件异常是否下料',
  'userConfig-MachineInfo-UseQieXyAndTieXcRecordMark': '启用切削液和铁屑槽记录的标志',
  'userConfig-MachineInfo-SplitBallChuckResultCoordinateX':
      '机床分中完成后(CNC是机床分中异常机床停在的坐标位置)EDM是机床分中完成后停在的位置坐标---武汉联塑使用',
  'userConfig-MachineInfo-SplitBallChuckResultCoordinateY':
      '机床分中完成后(CNC是机床分中异常机床停在的坐标位置)EDM是机床分中完成后停在的位置坐标---武汉联塑使用',
  'userConfig-MachineInfo-SplitBallChuckResultCoordinateZ':
      '机床分中完成后(CNC是机床分中异常机床停在的坐标位置)EDM是机床分中完成后停在的位置坐标---武汉联塑使用',
  'userConfig-MachineInfo-SplitBallChuckResultCoordinateU':
      '机床分中完成后(CNC是机床分中异常机床停在的坐标位置)EDM是机床分中完成后停在的位置坐标---武汉联塑使用',
  'userConfig-MachineInfo-SpAccuracyRange': '分中球精度范围',
  'userConfig-MachineInfo-SplitBallChuckCoordinateX': '分中球校验坐标X',
  'userConfig-MachineInfo-SplitBallChuckCoordinateY': '分中球校验坐标Y',
  'userConfig-MachineInfo-SplitBallChuckCoordinateZ': '分中球校验坐标Z',
  'userConfig-MachineInfo-SplitBallChuckCoordinateU': '分中球校验坐标U',
  'userConfig-MachineInfo-SteelPosBallMark': '钢件是否需要分中',
  'userConfig-MachineInfo-FlatnessChuckCoordinationX': '平面度检测校验坐标系X',
  'userConfig-MachineInfo-FlatnessChuckCoordinationY': '平面度检测校验坐标系Y',
  'userConfig-MachineInfo-FlatnessChuckCoordinationZ': '平面度检测校验坐标系Z',
  'userConfig-MachineInfo-FlatnessChuckCoordinationU': '平面度检测校验坐标系U',
  'userConfig-MachineInfo-FlatnessChuckAccuracyRange': '平面度检测精度范围',
  'userConfig-MachineInfo-ReferenceToMacHeadSpace': '基准台上表面~机头零点距离',
  'userConfig-MachineInfo-DistanceFromTubingToMacX': '吸油管相对于机头的位置X',
  'userConfig-MachineInfo-DistanceFromTubingToMacY': '吸油管相对于机头的位置Y',
  'userConfig-MachineInfo-DistanceFromTubingToMacZ': '吸油管相对于机头的位置Z',
  'userConfig-MachineInfo-DistanceFromTubingToMacU': '吸油管相对于机头的位置U',
  'userConfig-MachineInfo-PumpingFaultDistance': '抽油下降距离容错空间',
  'userConfig-MachineInfo-UpperChuckHeight': '上卡盘高度',
  'userConfig-MachineInfo-LowerChuckHeight': '下卡盘高度',
  'userConfig-MachineInfo-G54CoordinateZ': 'G54坐标Z值',
  'userConfig-MachineInfo-ChuckZeroCoordinateZ': '卡盘零点Z值',
  'userConfig-MachineInfo-ChuckCenterCoordinateX': '卡盘中心坐标X',
  'userConfig-MachineInfo-ChuckCenterCoordinateY': '卡盘中心坐标Y',
  'userConfig-MachineInfo-ChuckCenterCoordinateZ': '卡盘中心坐标Z',
  'userConfig-MachineInfo-ChuckCenterCoordinateU': '卡盘中心坐标U',
  'userConfig-PrgLocalInfo-LocalSrcPrgPath': 'PC端取点文件或未修改过的源加工程式保存路径',
  'userConfig-PrgLocalInfo-LocalMainPrgPath': 'PC端主程序路径',
  'userConfig-PrgLocalInfo-LocalSubPrgPath': 'PC端子程序路径',
  'userConfig-PrgLocalInfo-OrginPrgPath': 'PC端原点程式存放路径',
  'userConfig-PrgLocalInfo-KillTopPrgPath': 'PC端杀顶程序路径',
  'userConfig-PrgLocalInfo-EdmTemplatePrgPath': 'PC端放电模板程序路径',
  'userConfig-PrgServerInfo-FileServerType': '程序文件位置设置',
  'userConfig-PrgServerInfo-ServiceIP': 'FTP IP',
  'userConfig-PrgServerInfo-Port': 'FTP端口',
  'userConfig-PrgServerInfo-User': 'FTP用户',
  'userConfig-PrgServerInfo-Pwd': 'FTP密码',
  'userConfig-PrgServerInfo-Code': 'FTP采用编码（目前没有用到）',
  'userConfig-PrgServerInfo-SrcCmmElecPonitFileName':
      '电极源取点文件的命名规则，PartFileName或者ELECSN',
  'userConfig-PrgServerInfo-SrcCmmStPonitFileName':
      '钢件源取点文件的命名规则，PartFileName或者ELECSN',
  'userConfig-PrgServerInfo-SrcCncElecPrgName': '电极源加工程序名命名规则',
  'userConfig-PrgServerInfo-SrcCncStPrgName': '钢件源铣工程序名命名规则',
  'userConfig-PrgServerInfo-SrcLcncStPrgName': '钢件源车工程序名命名规则',
  'userConfig-PrgServerInfo-SrcEdmElecPrgName': '电极源放电程序名命名规则',
  'userConfig-PrgServerInfo-ExecCncElecPrgName': '电极加工执行程序名命名规则',
  'userConfig-PrgServerInfo-ExecCncStPrgName': '钢件铣工执行程序名命名规则',
  'userConfig-PrgServerInfo-ExecLcncStPrgName': '钢件车工执行程序名命名规则',
  'userConfig-PrgServerInfo-ExecEdmElecPrgName': '电极放电执行程序名命名规则',
  'userConfig-PrgServerInfo-CmmElecPointFileExtern': '电极检测取点文件后缀',
  'userConfig-PrgServerInfo-CmmStPointFileExtern': '钢件检测取点文件后缀',
  'userConfig-PrgServerInfo-SrcPrgExtern': '各系统类型对应的服务器上的源程式后缀',
  'userConfig-PrgServerInfo-ExecPrgExtern': '各系统类型对应的服务器上的执行程式后缀',
  'userConfig-PrgServerInfo-CmmElecPointPath': '电极检测取点文件路径',
  'userConfig-PrgServerInfo-CmmStPointPath': '钢件检测取点文件路径',
  'userConfig-PrgServerInfo-CncElecSrcPrgPath': '电极加工原始程序路径',
  'userConfig-PrgServerInfo-McncStSrcPrgPath': '钢件加工原始程序路径',
  'userConfig-PrgServerInfo-LcncStSrcPrgPath': '钢件车工原始程序路径',
  'userConfig-PrgServerInfo-CmmElecSrcPrgPath': '电极检测原始程序路径',
  'userConfig-PrgServerInfo-CmmStSrcPrgPath': '钢件检测原始程序路径',
  'userConfig-PrgServerInfo-EdmElecSrcPrgPath': '电极放电原始程序路径',
  'userConfig-PrgServerInfo-CncElecExecPrgPath': '电极加工执行程式文件路径',
  'userConfig-PrgServerInfo-CncStExecPrgPath': '钢件加工执行程式文件路径',
  'userConfig-PrgServerInfo-LcncStExecPrgPath': '钢件车工执行程式文件路径',
  'userConfig-PrgServerInfo-CmmElecExecPrgPath': '电极检测执行程式路径',
  'userConfig-PrgServerInfo-CmmStExecPrgPath': '钢件检测执行程式路径',
  'userConfig-PrgServerInfo-EdmPrgPath': '电极放电执行程式文件路径',
  'userConfig-PrgServerInfo-CmmElecReportSavePath':
      '电极结果文件拷贝至eact服务器判断是否合格(目前蔡司专用)',
  'userConfig-PrgServerInfo-CmmStReportSavePath':
      '钢件结果文件拷贝至eact服务器判断是否合格(目前蔡司专用)',
  'userConfig-PrgServerInfo-MacCheckResultFileName': '在机检测结果程序拷贝到目标路径的命名',
  'userConfig-PrgServerInfo-CopyMacCheckResultFilePath': '拷贝在机检测结果文件所到的路径',
  'userConfig-PrgServerInfo-CmmZiessTcpCopySrcPath': '拷贝的源程序路径',
  'userConfig-PrgServerInfo-CmmZiessTcpCopyDesPath': '拷贝的目标路径',
  'userConfig-EACTClientTcpInfo-ServerIp': 'EACT服务器IP  （与EACT客户端通讯）',
  'userConfig-EACTClientTcpInfo-ServerPort': 'EACT服务器端口',
  'userConfig-EACTClientTcpInfo-FancMode': '功能模式',
  'userConfig-DataBaseInfo-DBType': '数据库的类型',
  'userConfig-DataBaseInfo-OdbcName': '配置Windows ODBC时使用的连接名称 jingying',
  'userConfig-DataBaseInfo-DataSource': '数据库的 连接IP',
  'userConfig-DataBaseInfo-UserID': '数据库的用户名',
  'userConfig-DataBaseInfo-Password': '数据库的密码',
  'userConfig-DataBaseInfo-SqlPort':
      'SQL server 默认:1443，MYSQL默认:3306，QSQLITE无需端口',
  'userConfig-DataBaseInfo-UseDbXml': '标志查询',
  'userConfig-SysInfo-RunMode': '系统运行模式',
  'userConfig-SysInfo-CycleRun': '是否循环运行',
  'userConfig-SysInfo-ShelfIsOffLine': '单个货架加工/检测完成是否需要下线',
  'userConfig-SysInfo-AheadTaskWaitTime': '提前上料时等待时间拿回（分钟）',
  'userConfig-SysInfo-PrgDownMode': '程式下载类型',
  'userConfig-SysInfo-MachineOnlineSync': '机床关联设置1-2 互相关联，3-4互相关联',
  'userConfig-SysInfo-AddSteelSetOff': '钢件偏移量的标识',
  'userConfig-SysInfo-AddSteelClampFace': '钢件程序选面标识（精英扫描时查询程序用到）',
  'userConfig-SysInfo-OilTankReserve': '油槽上升的预留量,单位:毫米',
  'userConfig-SysInfo-RobotWaitFinishTime': '机器人任务发出去默认等待时间,单位：分钟',
  'userConfig-SysInfo-CheckElecCncToolMark': '检查电极加工刀具标志',
  'userConfig-SysInfo-CheckFenceDoorMark': '检查围栏门标志',
  'userConfig-SysInfo-CmmTimeoutRework': '自动返工检测时长(小时)',
  'userConfig-SysInfo-CmmSPsync': '是否开放SP',
  'userConfig-SysInfo-logPrintTimes': '部分日志的打印时间默认30天',
  'userConfig-SysInfo-CollectCycleTime': '采集线程时间单位：毫秒（1000毫秒为1秒）',
  'userConfig-SysInfo-CopyMode': '是否处理复制模---朝阳电子用',
  'userConfig-SysInfo-WorkpieceHeightSrc': '标记工件测高来源',
  'userConfig-SysInfo-ElecFixtureHeight': '电极的夹具高度',
  'userConfig-SysInfo-EdmDatumheight': '基准球高度',
  'userConfig-SysInfo-EdmDatumRadius': '基准球半径',
  'userConfig-SysInfo-CheckScheduleTimeMark': '查询数据库排程时间标志（目前只有武汉工程需要用到）',
  'userConfig-SysInfo-OvertimeAlarmDuration':
      '超时报警蜂鸣时长,单位：秒(配置多少秒后，蜂鸣取消，机器人继续)',
  'userConfig-SysInfo-MacToolManage': '标记机床是否有刀具管理',
  'userConfig-SysInfo-ReportSwitch': '报工开关',
  'userConfig-SysInfo-PreReportCheck': '前置报工校验，前置工艺没没扫成，设置异常',
  'userConfig-SysInfo-WorkpieceSpecLimit':
      '零件尺寸限制【毫米】（电极的长宽高限制分别为 120，120，120，钢件的长宽高限制分别为 140，140，125，为空，则不判断）',
  'userConfig-SysInfo-StorageSpace': '货位间距【毫米】(真实零件两边需各减去10毫米 得到80毫米)',
  'userConfig-SysInfo-EdmMoreSteelTask': '手动上钢件是否是多钢件连续放电',
  'userConfig-SysInfo-DealPlanProduceMark': '处理排产计划标志',
  'userConfig-SysInfo-SysName': '界面上显示的软件名称',
  'userConfig-SysInfo-ReWorkSelectPrgMark': '标记工艺返工是否 选程序,工艺 3，选择程序，工艺 4不选择程序',
  'userConfig-SysInfo-SysWareHouseName': '仓库名称#仓库号',
  'userConfig-SysInfo-ShelfOfflineMode': '当前机器人操作货架下线模式',
  'userConfig-SysInfo-ThreeDimensionalElectrodeMark': '标识校验电极是立体工的标识',
  'userConfig-SysInfo-HeadHightMark': '从eman获取高度---东泰用',
  'userConfig-SysInfo-ClampHightLowMark': '从eamn获取高度---东泰用',
  'userConfig-SysInfo-Dimensionalwork': '从eamn获取最低高度---东泰用',
  'userConfig-SysInfo-IsProcessQuadrantAngle': '是否需要调用修改象限角的exe',
  'userConfig-SysInfo-SteelCCNCFinishUpClean': '区分钢件粗加工完时否需要上清洗机',
  'userConfig-SysInfo-CheckProcessStepSwitch': '工艺区分工步开关',
  'userConfig-SysInfo-GetServerPrgWorkOrderMark': '获取服务器获上程序工单信息',
  'userConfig-SysInfo-ReallyProjectName': '项目名称',
  'userConfig-SysInfo-RobotCarryWorkpieceTaskType': '机器人把工件从装载站/接驳站搬运到货架的方式',
  'userConfig-SysInfo-positionerBall': '记录分中球的位置和芯片Id;例如货位号#条码#机床名',
  'userConfig-SysInfo-ToolLifeCollectMode': '刀具寿命采集模式',
  'userConfig-SysInfo-ToolLifeCollectTime': '刀具寿命采集循环时间，单位：分钟',
  'userConfig-SysInfo-AbnormalairIsOffLineMac': '机床气密性异常是否下线',
  'userConfig-SysInfo-SkipCraftReprocessCheck': '跳过工序校验结果表，配置在此的不需要校验结果表',
  'userConfig-FixtureInfo-AddFixtureType': ''
  // ui
};
